### ISSUE TITLE
Add `g:recent_bufstop_command` variable to enable delete the current opened file

### ISSUE THREAD

**Issue by bruhtus** [mihaifm/bufstop#23]
I've noticed that when I tried to delete opened/previewed file, bufstop take the entire window and because `g:BufstopDismissKey` using `:q` instead of `:bd`, bufstop quit vim instead of closing bufstop window.

My suggestion is to make `g:recent_bufstop_command` variable and delete the bufstop window, after that calling the bufstop command according to `g:recent_bufstop_command`.

Here's an example if we use it on default `Bufstop` command:
```vim
" wrapper for Bufstop(), default mode
function! BufstopSlow()
  let g:recent_bufstop_command = 'Bufstop'
  let s:fast_mode = 0
  let s:preview_mode = 0
  call Bufstop()
  call s:UnmapPreviewKeys()
endfunction

---

" `bufwinnr` is to check if the buffer is open/visible
if bufwinnr(s:bufnr) ># 0
 call remove(s:allbufs, line('.')-1)
 exe "silent bd ".s:bufnr
 setlocal modifiable
 exe "d"
 setlocal nomodifiable
 bd
 If g:recent_bufstop_command ==# 'Bufstop'
   call BufstopSlow()
 endif

else
 call remove(s:allbufs, line('.')-1)
 exe "silent bd ".s:bufnr
 setlocal modifiable
 exe "d"
 setlocal nomodifiable

endif
```

and for the dismiss key, we can use:
```vim
exe "nnoremap <buffer> <silent> " . g:BufstopDismissKey . " :bd \| unlet g:recent_bufstop_command<cr><C-w>p"
```

I'm still not sure how to do that in `BufstopPreview` tho. So, what do you think?

**Comment by mihaifm** [comment]
Not sure I understand the issue. Only when you have a single file in opened vim and you delete it in bufstop, it indeed quits vim. Are you saying it should only delete the buffer and keep vim open?

**Comment by bruhtus** [comment]
> Only when you have a single file in opened vim and you delete it in bufstop, it indeed quits vim.

The problem is, it quit vim even though it is not the only buffer in vim.

Here's an example scenario: <br>
- you open multiple file inside vim
- you use `BufstopPreview` command
- you moving between opened buffer using `j`/`k`, and then decided to delete only the buffer at the cursor (the file should be opened if we use `BufstopPreview`)
- it close the buffer and make `Bufstop` window larger
- you tried to exit `Bufstop` window using `Dismiss Key` but it closes vim (even tho there's still hidden buffer around)

**Comment by mihaifm** [comment]
Ah, I see now. It's a bug indeed, thanks for the replications steps.

**Comment by bruhtus** [comment]
Glad I could help. My solution is still rough, maybe you can find a better one :)

**Comment by mihaifm** [comment]
The problem is that the BufstopPreview command always loads the buffer in a window, so when you are trying to delete it, Vim also closes the respective window.

The solution is to always load a different buffer (basically the first one in the list) in the window before wiping the buffer. If there is only one buffer in Vim and you're trying to delete it, a dummy one is created to prevent the window being closed. 

I pushed a commit with this fix, can you test it? It should greatly improve the buffer delete experience.

**Comment by bruhtus** [comment]
It fix the issue and the Bufstop key still the same, thanks!

Hopefully no one gonna close the last buffer using Bufstop 😅

Oh, another suggestion. I think you can make Bufstop close vim if bufstop is the last opened window by doing something like this:
```vim
if winnr('s') == 1 && &buftype == 'nofile' | q | endif
```
in `BufstopDismissKey` mapping. I haven't tried it yet so I'm not sure if it gonna work, or maybe you can find a better solution again!

Alright, I'm gonna close this now. Thanks again!

**Comment by bruhtus** [comment]
Sorry to re-open this issue 😅

I found some interesting behaviour when closing visible buffer in split window, Bufstop didn't close the split window if we closed the buffer.

Here's an example scenario:
- open a file
- open a second file in split window (whether horizontal/vertical)
- use `BufstopPreview`  and move to the first file, and then delete the first file
- now we have the same file opened in two window

It's not really bothering like the main issue, but I just want to mention it to you just in case someone use bufstop with split window. You can close this again if you want 😅

**Comment by mihaifm** [comment]
Yea, it's expected. So Bufstop doesn't close windows, only buffers. The goal is to actually preserve window layout. The behavior is like this:

- if you delete a buffer that is opened in a window, it will load the first buffer in that window
- if you try to delete the first buffer and that is open in a window, it will load the second buffer instead
- if there is only one buffer, it will create a dummy buffer instead of it

Let me know if you find any other issues. Cheers

**Comment by bruhtus** [comment]
Ah I see, I thought Bufstop also close the windows. Maybe you should add those information in readme so that the new user doesn't think it was a bug.

I'll let you know if there's other issue, for now it works great. Thanks!
